# Site settings
title: Jonathan Shields portfolio site
author:
  name: Jonathan Shields
  email: jps1608@googlemail.com
description: "Jonathan Shields's portfolio site"

# Build settings
remote_theme: jekyll/modernist